// countries.js

export const countries_en = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia (Czech Republic)',
    'Democratic Republic of the Congo (Congo-Kinshasa)',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor-Leste)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini (fmr. "Swaziland")',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (formerly Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia (formerly Macedonia)',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];
  
  export const countries_ru = [
    'Афганистан',
    'Албания',
    'Алжир',
    'Андорра',
    'Ангола',
    'Антигуа и Барбуда',
    'Аргентина',
    'Армения',
    'Австралия',
    'Австрия',
    'Азербайджан',
    'Багамы',
    'Бахрейн',
    'Бангладеш',
    'Барбадос',
    'Беларусь',
    'Бельгия',
    'Белиз',
    'Бенин',
    'Бутан',
    'Боливия',
    'Босния и Герцеговина',
    'Ботсвана',
    'Бразилия',
    'Бруней',
    'Болгария',
    'Буркина-Фасо',
    'Бурунди',
    'Кабо-Верде',
    'Камбоджа',
    'Камерун',
    'Канада',
    'Центральноафриканская Республика',
    'Чад',
    'Чили',
    'Китай',
    'Колумбия',
    'Коморские Острова',
    'Конго (Конго-Браззавиль)',
    'Коста-Рика',
    'Хорватия',
    'Куба',
    'Кипр',
    'Чехия (Чешская Республика)',
    'Демократическая Республика Конго (Конго-Киншаса)',
    'Дания',
    'Джибути',
    'Доминика',
    'Доминиканская Республика',
    'Восточный Тимор (Тимор-Лешти)',
    'Эквадор',
    'Египет',
    'Сальвадор',
    'Экваториальная Гвинея',
    'Эритрея',
    'Эстония',
    'Эсватини (бывш. Свазиленд)',
    'Эфиопия',
    'Фиджи',
    'Финляндия',
    'Франция',
    'Габон',
    'Гамбия',
    'Грузия',
    'Германия',
    'Гана',
    'Греция',
    'Гренада',
    'Гватемала',
    'Гвинея',
    'Гвинея-Бисау',
    'Гайана',
    'Гаити',
    'Гондурас',
    'Венгрия',
    'Исландия',
    'Индия',
    'Индонезия',
    'Иран',
    'Ирак',
    'Ирландия',
    'Израиль',
    'Италия',
    'Кот д`Ивуар',
    'Ямайка',
    'Япония',
    'Иордания',
    'Казахстан',
    'Кения',
    'Кирибати',
    'КНДР',
    'Республика Корея',
    'Косово',
    'Кувейт',
    'Кыргызстан',
    'Лаос',
    'Латвия',
    'Ливан',
    'Лесото',
    'Либерия',
    'Ливия',
    'Лихтенштейн',
    'Литва',
    'Люксембург',
    'Мадагаскар',
    'Малави',
    'Малайзия',
    'Мальдивы',
    'Мали',
    'Мальта',
    'Маршалловы Острова',
    'Мавритания',
    'Маврикий',
    'Мексика',
    'Микронезия',
    'Молдова',
    'Монако',
    'Монголия',
    'Черногория',
    'Марокко',
    'Мозамбик',
    'Мьянма (бывш. Бирма)',
    'Намибия',
    'Науру',
    'Непал',
    'Нидерланды',
    'Новая Зеландия',
    'Никарагуа',
    'Нигер',
    'Нигерия',
    'Северная Македония (бывш. Македония)',
    'Норвегия',
    'Оман',
    'Пакистан',
    'Палау',
    'Государство Палестина',
    'Панама',
    'Папуа-Новая Гвинея',
    'Парагвай',
    'Перу',
    'Филиппины',
    'Польша',
    'Португалия',
    'Катар',
    'Румыния',
    'Россия',
    'Руанда',
    'Сент-Китс и Невис',
    'Сент-Люсия',
    'Сент-Винсент и Гренадины',
    'Самоа',
    'Сан-Марино',
    'Сан-Томе и Принсипи',
    'Саудовская Аравия',
    'Сенегал',
    'Сербия',
    'Сейшельские Острова',
    'Сьерра-Леоне',
    'Сингапур',
    'Словакия',
    'Словения',
    'Соломоновы Острова',
    'Сомали',
    'Южно-Африканская Республика',
    'Южный Судан',
    'Испания',
    'Шри-Ланка',
    'Судан',
    'Суринам',
    'Швеция',
    'Швейцария',
    'Сирия',
    'Тайвань',
    'Таджикистан',
    'Танзания',
    'Таиланд',
    'Того',
    'Тонга',
    'Тринидад и Тобаго',
    'Тунис',
    'Турция',
    'Туркменистан',
    'Тувалу',
    'Уганда',
    'Украина',
    'Объединенные Арабские Эмираты',
    'Великобритания',
    'Соединенные Штаты Америки',
    'Уругвай',
    'Узбекистан',
    'Вануату',
    'Ватикан',
    'Венесуэла',
    'Вьетнам',
    'Йемен',
    'Замбия',
    'Зимбабве',
  ];
  export const countries_fr = [
    'Afghanistan',
    'Albanie',
    'Algérie',
    'Andorre',
    'Angola',
    'Antigua-et-Barbuda',
    'Argentine',
    'Arménie',
    'Australie',
    'Autriche',
    'Azerbaïdjan',
    'Bahamas',
    'Bahreïn',
    'Bangladesh',
    'Barbade',
    'Biélorussie',
    'Belgique',
    'Belize',
    'Bénin',
    'Bhoutan',
    'Bolivie',
    'Bosnie-Herzégovine',
    'Botswana',
    'Brésil',
    'Brunei',
    'Bulgarie',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodge',
    'Cameroun',
    'Canada',
    'République centrafricaine',
    'Tchad',
    'Chili',
    'Chine',
    'Colombie',
    'Comores',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatie',
    'Cuba',
    'Chypre',
    'Tchéquie (République tchèque)',
    'République démocratique du Congo (Congo-Kinshasa)',
    'Danemark',
    'Djibouti',
    'Dominique',
    'République dominicaine',
    'Timor oriental (Timor-Leste)',
    'Équateur',
    'Égypte',
    'Salvador',
    'Guinée équatoriale',
    'Érythrée',
    'Estonie',
    'Eswatini (anciennement "Swaziland")',
    'Éthiopie',
    'Fidji',
    'Finlande',
    'France',
    'Gabon',
    'Gambie',
    'Géorgie',
    'Allemagne',
    'Ghana',
    'Grèce',
    'Grenade',
    'Guatemala',
    'Guinée',
    'Guinée-Bissau',
    'Guyana',
    'Haïti',
    'Honduras',
    'Hongrie',
    'Islande',
    'Inde',
    'Indonésie',
    'Iran',
    'Irak',
    'Irlande',
    'Israël',
    'Italie',
    "Côte d'Ivoire",
    'Jamaïque',
    'Japon',
    'Jordanie',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Corée du Nord',
    'Corée du Sud',
    'Kosovo',
    'Koweït',
    'Kirghizistan',
    'Laos',
    'Lettonie',
    'Liban',
    'Lesotho',
    'Libéria',
    'Libye',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaisie',
    'Maldives',
    'Mali',
    'Malte',
    'Îles Marshall',
    'Mauritanie',
    'Maurice',
    'Mexique',
    'Micronésie',
    'Moldavie',
    'Monaco',
    'Mongolie',
    'Monténégro',
    'Maroc',
    'Mozambique',
    'Myanmar (anciennement Birmanie)',
    'Namibie',
    'Nauru',
    'Népal',
    'Pays-Bas',
    'Nouvelle-Zélande',
    'Nicaragua',
    'Niger',
    'Nigéria',
    'Macédoine du Nord (anciennement Macédoine)',
    'Norvège',
    'Oman',
    'Pakistan',
    'Palaos',
    'État de Palestine',
    'Panama',
    'Papouasie-Nouvelle-Guinée',
    'Paraguay',
    'Pérou',
    'Philippines',
    'Pologne',
    'Portugal',
    'Qatar',
    'Roumanie',
    'Russie',
    'Rwanda',
    'Saint-Christophe-et-Niévès',
    'Sainte-Lucie',
    'Saint-Vincent-et-les Grenadines',
    'Samoa',
    'Saint-Marin',
    'Sao Tomé-et-Principe',
    'Arabie saoudite',
    'Sénégal',
    'Serbie',
    'Seychelles',
    'Sierra Leone',
    'Singapour',
    'Slovaquie',
    'Slovénie',
    'Îles Salomon',
    'Somalie',
    'Afrique du Sud',
    'Soudan du Sud',
    'Espagne',
    'Sri Lanka',
    'Soudan',
    'Suriname',
    'Suède',
    'Suisse',
    'Syrie',
    'Taïwan',
    'Tadjikistan',
    'Tanzanie',
    'Thaïlande',
    'Togo',
    'Tonga',
    'Trinité-et-Tobago',
    'Tunisie',
    'Turquie',
    'Turkménistan',
    'Tuvalu',
    'Ouganda',
    'Ukraine',
    'Émirats arabes unis',
    'Royaume-Uni',
    "États-Unis d'Amérique",
    'Uruguay',
    'Ouzbékistan',
    'Vanuatu',
    'Cité du Vatican',
    'Venezuela',
    'Vietnam',
    'Yémen',
    'Zambie',
    'Zimbabwe',
];
export const countries_es = [
  'Afganistán',
  'Albania',
  'Argelia',
  'Andorra',
  'Angola',
  'Antigua y Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Baréin',
  'Bangladesh',
  'Barbados',
  'Bielorrusia',
  'Bélgica',
  'Belice',
  'Benín',
  'Bután',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'República Centroafricana',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoras',
  'Congo (Brazzaville)',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Chipre',
  'República Checa',
  'República Democrática del Congo (Kinshasa)',
  'Dinamarca',
  'Yibuti',
  'Dominica',
  'República Dominicana',
  'Timor Oriental (Timor-Leste)',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Guinea Ecuatorial',
  'Eritrea',
  'Estonia',
  'Esuatini (anteriormente Suazilandia)',
  'Etiopía',
  'Fiyi',
  'Finlandia',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Alemania',
  'Ghana',
  'Grecia',
  'Granada',
  'Guatemala',
  'Guinea',
  'Guinea-Bisáu',
  'Guyana',
  'Haití',
  'Honduras',
  'Hungría',
  'Islandia',
  'India',
  'Indonesia',
  'Irán',
  'Irak',
  'Irlanda',
  'Israel',
  'Italia',
  'Costa de Marfil',
  'Jamaica',
  'Japón',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kiribati',
  'Corea del Norte',
  'Corea del Sur',
  'Kosovo',
  'Kuwait',
  'Kirguistán',
  'Laos',
  'Letonia',
  'Líbano',
  'Lesoto',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Madagascar',
  'Malaui',
  'Malasia',
  'Maldivas',
  'Malí',
  'Malta',
  'Islas Marshall',
  'Mauritania',
  'Mauricio',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Mongolia',
  'Montenegro',
  'Marruecos',
  'Mozambique',
  'Myanmar (Birmania)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Países Bajos',
  'Nueva Zelanda',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Macedonia del Norte (anteriormente Macedonia)',
  'Noruega',
  'Omán',
  'Pakistán',
  'Palaos',
  'Estado de Palestina',
  'Panamá',
  'Papúa Nueva Guinea',
  'Paraguay',
  'Perú',
  'Filipinas',
  'Polonia',
  'Portugal',
  'Catar',
  'Rumania',
  'Rusia',
  'Ruanda',
  'San Cristóbal y Nieves',
  'Santa Lucía',
  'San Vicente y las Granadinas',
  'Samoa',
  'San Marino',
  'Santo Tomé y Príncipe',
  'Arabia Saudita',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Eslovaquia',
  'Eslovenia',
  'Islas Salomón',
  'Somalia',
  'Sudáfrica',
  'Sudán',
  'Surinam',
  'Suecia',
  'Suiza',
  'Siria',
  'Taiwán',
  'Tayikistán',
  'Tanzania',
  'Tailandia',
  'Togo',
  'Tonga',
  'Trinidad y Tobago',
  'Túnez',
  'Turquía',
  'Turkmenistán',
  'Tuvalu',
  'Uganda',
  'Ucrania',
  'Emiratos Árabes Unidos',
  'Reino Unido',
  'Estados Unidos de América',
  'Uruguay',
  'Uzbekistán',
  'Vanuatu',
  'Ciudad del Vaticano',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabue',
];
