export const defaultFormValues = {
  Email: "",
  ContactPersonName: "",
  PreferredContactMeans: "",
  ContactPersonPosition: "",
  CountryID: null,
  OrganizationType: "",
  Municipality: "",
  OrganizationName: "",
  ActorTypeID: null,
  ExistingProgramStatus: false,
  TrainingInterest: "",
  ImplementationScale: "",
  InvolvementCapability: "",
  TargetedFarmerCommunitySize: null,
  DevelopedEducationalMaterialStatus: false,
  AccessToFunds: false,
  AgreedToTOR: false,
  Feedback: "",
  DateOfRegistration: null,
  PromoterStatus: "Awaiting Reply",
  ReplyDate: null,
  ReplyContent: null,
  ActorType: "",
  MapInstitutionName: null,
  RegisteredInMap: false,
  Comments: null,
};
