export const labels = {
    pending: {
        en: "Your application is still pending review.",
        ru: "Ваша заявка все еще находится на рассмотрении.",
        es: "Su solicitud todavía está pendiente de revisión.",
        fr: "Votre demande est toujours en cours d'examen."
      },    
      revisitlink: {
          en: "Please re-visit this link once you have been contacted to check your application's progress.",
          ru: "Пожалуйста, перейдите по этой ссылке еще раз после того как с вами свяжутся, чтобы проверить статус вашей заявки.",
          es: "Por favor, vuelva a visitar este enlace una vez que hayan contactado con usted para verificar el progreso de su solicitud.",
          fr: "Veuillez revisiter ce lien une fois que vous avez été contacté pour vérifier l'avancement de votre demande."
      },
    en: {
        email: "Email:",
        contactName: "Name of the contact person:",
        contactPreference: "Please provide details about the preferred mean to contact you to facilitate our collaboration (personal email/cell phone/WhatsApp/Social networks):",
        contactPosition: "Position of the contact person:",
        region: "Region:",
        country: "Country:",
        municipality: "Municipality:",
        orgName: "Institution / Organization name:",
        orgType: "Institution / Organization type:",
        ongoingProgram: "Is there already an ongoing programme similar to the Soil Doctors in your country/region?",
        soilTopics: "Are you interested to develop trainings based on one or more specific soil topic?",
        implementationScale: "Which would be the scale of the implementation?",
        involveInstitutions: "Will you be able to involve other national or regional institutions/organizations? (other promoters, extension services, government, academia, NGOs…)",
        targetCommunitySize: "How large is the target farmer community you would like to start the implementation with?",
        developedMaterials: "Have you already developed educational material on soil? (videos, posters, trainings)",
        accessToFunds: "Do you have access to funds to ensure the sustainability of the programme?",
        agreementWithToR: "Did you read and agree with the ToR?",
        feedback:"Your feedback is valuable to us, and can help us improve the programme over time and tailor it to promoters’ and farmers’ needs. Please also do not hesitate to contact us at ",
        submit: "Submit",
        actorType: 'What type of actor are you applying for?',
        currentStage: 'Current stage of application',
        institutionNameForMap: 'Institution name for the map',

    },
    ru: {
        email: "Электронная почта:",
        contactName: "Имя контактного лица:",
        contactPreference: "Пожалуйста, предоставьте данные о предпочтительном способе связи с вами для улучшения нашего сотрудничества (личный email/мобильный телефон/WhatsApp/социальные сети):",
        contactPosition: "Должность контактного лица:",
        region: "Регион:",
        country: "Страна:",
        municipality: "Муниципалитет:",
        orgName: "Название института / организации:",
        orgType: "Тип института / организации:",
        ongoingProgram: "Есть ли уже действующая программа, аналогичная Soil Doctors, в вашей стране/регионе?",
        soilTopics: "Интересуетесь ли вы разработкой обучающих программ на основе одной или нескольких конкретных тем почвоведения?",
        implementationScale: "Каков масштаб реализации?",
        involveInstitutions: "Сможете ли вы привлечь другие национальные или региональные институты/организации? (другие инициаторы, службы продвижения, государственные органы, академия, НКО и др.)",
        targetCommunitySize: "Каков размер целевого фермерского сообщества, с которым вы хотели бы начать реализацию?",
        developedMaterials: "Уже ли у вас есть образовательные материалы по почвоведению? (видео, плакаты, обучение)",
        accessToFunds: "Имеете ли вы доступ к финансовым ресурсам для обеспечения устойчивости программы?",
        agreementWithToR: "Вы прочитали и согласны с ТЗ (техническим заданием)?",
        feedback:"Ваши отзывы ценны для нас и могут помочь нам улучшить программу с течением времени и адаптировать ее к потребностям промоутеров и фермеров. Пожалуйста, также не стесняйтесь обращаться к нам по адресу",
        submit: "Отправить",
        actorType: 'Какого типа актера вы хотите выбрать?',
        currentStage: 'Текущий этап заявки',
        institutionNameForMap: 'Название учреждения для карты',
    },
    es: {
        email: "Correo electrónico:",
        contactName: "Nombre de la persona de contacto:",
        contactPreference: "Por favor, proporcione detalles sobre el medio preferido para ponerse en contacto con usted y facilitar nuestra colaboración (correo electrónico personal / teléfono móvil / WhatsApp / redes sociales):",
        contactPosition: "Cargo de la persona de contacto:",
        region: "Región:",
        country: "País:",
        municipality: "Municipio:",
        orgName: "Nombre de la institución / organización:",
        orgType: "Tipo de institución / organización:",
        ongoingProgram: "¿Ya existe un programa en curso similar a Soil Doctors en su país/región?",
        soilTopics: "¿Está interesado en desarrollar capacitaciones basadas en uno o varios temas específicos de la tierra?",
        implementationScale: "¿Cuál sería la escala de implementación?",
        involveInstitutions: "¿Podrá involucrar a otras instituciones u organizaciones nacionales o regionales? (otros promotores, servicios de extensión, gobierno, academia, ONG, etc.)",
        targetCommunitySize: "¿Cuán grande es la comunidad de agricultores objetivo con la que le gustaría comenzar la implementación?",
        developedMaterials: "¿Ya ha desarrollado material educativo sobre la tierra? (videos, carteles, capacitaciones)",
        accessToFunds: "¿Tiene acceso a fondos para garantizar la sostenibilidad del programa?",
        agreementWithToR: "¿Ha leído y está de acuerdo con el TdR (términos de referencia)?",
        feedback:"Sus comentarios son muy valiosos para nosotros y pueden ayudarnos a mejorar el programa con el tiempo y a adaptarlo a las necesidades de los promotores y agricultores. No dude en ponerse en contacto con nosotros en ",
        submit: "Enviar",
        actorType: 'Quel type d\'acteur souhaitez-vous appliquer?',
        currentStage: 'Etapa actual de la solicitud',
        institutionNameForMap: 'Nombre de la institución para el mapa',
        
        
        
    },    fr: {
        email: "E-mail :",
        contactName: "Nom de la personne de contact :",
        contactPreference: "Veuillez fournir des détails sur le moyen préféré de vous contacter pour faciliter notre collaboration (e-mail personnel/téléphone portable/WhatsApp/réseaux sociaux) :",
        contactPosition: "Poste de la personne de contact :",
        region: "Région :",
        country: "Pays :",
        municipality: "Municipalité :",
        orgName: "Nom de l'institution / de l'organisation :",
        orgType: "Type de l'institution / de l'organisation :",
        ongoingProgram: "Y a-t-il déjà un programme en cours similaire à Soil Doctors dans votre pays/région ?",
        soilTopics: "Êtes-vous intéressé à développer des formations basées sur un ou plusieurs sujets spécifiques liés aux sols ?",
        implementationScale: "Quelle serait l'échelle de mise en œuvre ?",
        involveInstitutions: "Serez-vous en mesure d'impliquer d'autres institutions ou organisations nationales ou régionales ? (autres promoteurs, services d'extension, gouvernement, universités, ONG, etc.)",
        targetCommunitySize: "Quelle est la taille de la communauté d'agriculteurs cible avec laquelle vous souhaitez commencer la mise en œuvre ?",
        developedMaterials: "Avez-vous déjà développé du matériel éducatif sur les sols ? (vidéos, affiches, formations)",
        accessToFunds: "Avez-vous accès à des fonds pour assurer la durabilité du programme ?",
        agreementWithToR: "Avez-vous lu et accepté les Termes de Référence (TdR) ?",
        feedback:"Vos commentaires sont précieux pour nous et peuvent nous aider à améliorer le programme et à l'adapter aux besoins des promoteurs et des agriculteurs. N'hésitez pas non plus à nous contacter à l'adresse ",
        submit: "Soumettre",
        actorType: '¿Para qué tipo de actor estás aplicando?',
        currentStage: 'Étape actuelle de la demande',
        institutionNameForMap: 'Nom de l’institution pour la carte',
    }
    // Add more languages here
  };
  